import { z } from 'zod';

const id = z.string().uuid();
const json = z.record(z.any());

export function registerPhase89FacilityPlatformRoutes(app:any,pool:any,deps:any){
  const {dbOrganizationId,dbUserId,requireAuthorizedWrite,dbAudit}=deps;
  const oid=(req:any)=>dbOrganizationId(req);
  const noDb=(reply:any)=>reply.code(501).send({error:'Clinical data service is unavailable.'});
  const list=async(sql:string,params:any[])=>{const r=await pool.query(sql,params);return {data:r.rows,count:r.rowCount??0};};

  const queries:Record<string,string>={
    staff:`SELECT h.id,h.user_id AS "userId",u.display_name AS "displayName",u.email,h.facility_id AS "facilityId",h.cadre,h.profession,h.registration_system AS "registrationSystem",h.registration_number AS "registrationNumber",h.specialty,h.status,h.department,h.role,h.shift,h.availability_status AS "availabilityStatus",h.leave_status AS "leaveStatus",h.workload,h.license_expiry AS "licenseExpiry",h.credentials,h.verified_at AS "verifiedAt" FROM health_worker_profiles h JOIN users u ON u.id=h.user_id WHERE h.organization_id=$1 ORDER BY u.display_name`,
    facilities:`SELECT f.id,f.name,f.type,f.timezone,COALESCE((SELECT count(*) FROM health_worker_profiles h WHERE h.organization_id=$1 AND h.facility_id=f.id),0)::int AS "staffCount",COALESCE((SELECT count(*) FROM facility_operational_incidents i WHERE i.organization_id=$1 AND i.facility_id=f.id AND i.status NOT IN ('resolved','closed')),0)::int AS "openIncidents",COALESCE((SELECT sum(c.capacity_total) FROM facility_service_capacity c WHERE c.organization_id=$1 AND c.facility_id=f.id),0)::numeric AS "capacityTotal",COALESCE((SELECT sum(c.capacity_available) FROM facility_service_capacity c WHERE c.organization_id=$1 AND c.facility_id=f.id),0)::numeric AS "capacityAvailable" FROM facilities f WHERE f.organization_id=$1 ORDER BY f.name`,
    'facility-capacity':`SELECT c.*,f.name AS "facilityName",f.type AS "facilityType" FROM facility_service_capacity c JOIN facilities f ON f.id=c.facility_id WHERE c.organization_id=$1 ORDER BY c.observed_at DESC LIMIT 500`,
    'facility-resources':`SELECT r.*,f.name AS "facilityName",f.type AS "facilityType" FROM facility_resource_status r JOIN facilities f ON f.id=r.facility_id WHERE r.organization_id=$1 ORDER BY r.observed_at DESC LIMIT 500`,
    'facility-incidents':`SELECT i.*,f.name AS "facilityName" FROM facility_operational_incidents i LEFT JOIN facilities f ON f.id=i.facility_id WHERE i.organization_id=$1 ORDER BY CASE i.severity WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'moderate' THEN 3 ELSE 4 END,i.started_at DESC LIMIT 500`,
    'facility-performance':`SELECT p.*,f.name AS "facilityName" FROM facility_performance_snapshots p LEFT JOIN facilities f ON f.id=p.facility_id WHERE p.organization_id=$1 ORDER BY p.period_end DESC,p.created_at DESC LIMIT 500`,
    interoperability:`SELECT c.id,c.name AS system,c.protocol AS standard,c.base_url AS endpoint,c.status,c.jurisdiction,c.capabilities,c.last_success_at AS "lastSuccessAt",c.last_error AS "lastError",COALESCE(m.message_count,0)::int AS "messageCount",COALESCE(m.failed_count,0)::int AS "failedMessages" FROM hie_connections c LEFT JOIN (SELECT connection_id,count(*) AS message_count,count(*) FILTER(WHERE status='failed') AS failed_count FROM hie_messages WHERE organization_id=$1 GROUP BY connection_id)m ON m.connection_id=c.id WHERE c.organization_id=$1 ORDER BY c.name`,
    'health-connections':`SELECT c.id,c.name,c.jurisdiction,c.protocol,c.base_url AS "baseUrl",c.status,c.capabilities,c.credential_ref AS "credentialRef",c.last_success_at AS "lastSuccessAt",c.last_error AS "lastError",COALESCE(m.message_count,0)::int AS "messageCount",COALESCE(m.failed_count,0)::int AS "failedMessages" FROM hie_connections c LEFT JOIN (SELECT connection_id,count(*) AS message_count,count(*) FILTER(WHERE status='failed') AS failed_count FROM hie_messages WHERE organization_id=$1 GROUP BY connection_id)m ON m.connection_id=c.id WHERE c.organization_id=$1 ORDER BY c.name`,
    audit:`SELECT id,actor_user_id AS "actorUserId",action,entity_type AS "entityType",entity_id AS "entityId",metadata,created_at AS "createdAt" FROM audit_logs WHERE organization_id=$1 ORDER BY created_at DESC LIMIT 500`,
    security:`SELECT id,user_id AS "userId",patient_id AS "patientId",event_type AS "eventType",severity,reason,metadata,created_at AS "createdAt",'security' AS source FROM security_events WHERE organization_id=$1 UNION ALL SELECT id,user_id AS "userId",patient_id AS "patientId",event_type AS "eventType",severity,NULL::text AS reason,metadata,created_at AS "createdAt",'ai-security' AS source FROM ai_security_events WHERE organization_id=$1 ORDER BY "createdAt" DESC LIMIT 500`,
    settings:`SELECT id,category,name,value,value_type AS "valueType",description,created_at AS "createdAt",updated_at AS "updatedAt" FROM organization_settings WHERE organization_id=$1 ORDER BY category,name`,
    terminology:`SELECT id,system_uri AS "systemUri",code,display,version,status,source,source_url AS "sourceUrl",properties,created_at AS "createdAt" FROM terminology_concepts WHERE organization_id=$1 OR organization_id IS NULL ORDER BY display LIMIT 500`,
    guidelines:`SELECT id,title,domain,jurisdiction,publisher,version,source_url AS "sourceUrl",effective_from AS "effectiveFrom",effective_to AS "effectiveTo",status,machine_readable AS "machineReadable",metadata,created_at AS "createdAt" FROM clinical_guidelines WHERE organization_id=$1 OR organization_id IS NULL ORDER BY updated_at DESC LIMIT 500`,
    'care-pathways':`SELECT p.id,p.name,p.code,p.domain,p.jurisdiction,p.status,p.version,p.source_guideline_id AS "sourceGuidelineId",p.metadata,p.created_at AS "createdAt",(SELECT count(*) FROM care_pathway_steps s WHERE s.pathway_id=p.id)::int AS "stepCount" FROM care_pathways p WHERE p.organization_id=$1 OR p.organization_id IS NULL ORDER BY p.updated_at DESC LIMIT 500`,
    reporting:`SELECT id,reporting_system AS "reportingSystem",period_start AS "periodStart",period_end AS "periodEnd",payload,status,external_reference AS "externalReference",error,created_by AS "createdBy",created_at AS "createdAt",submitted_at AS "submittedAt" FROM reporting_submissions WHERE organization_id=$1 ORDER BY created_at DESC LIMIT 500`,
    'offline-sync':`SELECT q.id,q.device_id AS "deviceId",q.user_id AS "userId",q.operation_id AS "operationId",q.resource_type AS "resourceType",q.resource_id AS "resourceId",q.operation,q.payload,q.base_version AS "baseVersion",q.status,q.conflict,q.attempts,q.created_at AS "createdAt",q.synced_at AS "syncedAt",d.platform,d.app_version AS "appVersion",d.last_seen_at AS "lastSeenAt",d.last_sync_at AS "lastSyncAt" FROM offline_sync_queue q LEFT JOIN sync_devices d ON d.organization_id=q.organization_id AND d.device_id=q.device_id WHERE q.organization_id=$1 ORDER BY q.created_at DESC LIMIT 500`
  };

  const phaseModules=Object.keys(queries);

  async function dashboard(req:any,module:string){
    const o=oid(req);
    const map:Record<string,{kpis:string[],trend:string,breakdown:string}>={
      facilities:{kpis:[`SELECT count(*)::int n FROM facilities WHERE organization_id=$1`,`SELECT count(*)::int n FROM health_worker_profiles WHERE organization_id=$1 AND status='active'`,`SELECT count(*)::int n FROM facility_operational_incidents WHERE organization_id=$1 AND status NOT IN ('resolved','closed')`,`SELECT COALESCE(sum(capacity_available),0)::numeric n FROM facility_service_capacity WHERE organization_id=$1`],trend:`SELECT to_char(date_trunc('day',created_at),'YYYY-MM-DD') AS "day",count(*)::int AS "count" FROM facilities WHERE organization_id=$1 AND created_at>=now()-interval '30 days' GROUP BY 1 ORDER BY 1`,breakdown:`SELECT type label,count(*)::int count FROM facilities WHERE organization_id=$1 GROUP BY type ORDER BY count DESC`},
      staff:{kpis:[`SELECT count(*)::int n FROM health_worker_profiles WHERE organization_id=$1`,`SELECT count(*)::int n FROM health_worker_profiles WHERE organization_id=$1 AND status='active'`,`SELECT COALESCE(sum(on_duty_count),0)::int n FROM workforce_capacity_snapshots w WHERE w.organization_id=$1 AND w.snapshot_at=(SELECT max(w2.snapshot_at) FROM workforce_capacity_snapshots w2 WHERE w2.organization_id=w.organization_id AND COALESCE(w2.facility_id,'00000000-0000-0000-0000-000000000000')=COALESCE(w.facility_id,'00000000-0000-0000-0000-000000000000') AND w2.cadre=w.cadre)`,`SELECT count(*)::int n FROM health_worker_profiles WHERE organization_id=$1 AND license_expiry IS NOT NULL AND license_expiry<=current_date+30 AND license_expiry>=current_date`],trend:`SELECT to_char(date_trunc('day',created_at),'YYYY-MM-DD') label,count(*)::int count FROM health_worker_profiles WHERE organization_id=$1 AND created_at>=now()-interval '30 days' GROUP BY 1 ORDER BY 1`,breakdown:`SELECT cadre label,count(*)::int count FROM health_worker_profiles WHERE organization_id=$1 GROUP BY cadre ORDER BY count DESC`},
      'facility-capacity':{kpis:[`SELECT count(*)::int n FROM facility_service_capacity WHERE organization_id=$1`,`SELECT count(*)::int n FROM facility_service_capacity WHERE organization_id=$1 AND status='available'`,`SELECT COALESCE(sum(capacity_total),0)::numeric n FROM facility_service_capacity WHERE organization_id=$1`,`SELECT COALESCE(sum(capacity_available),0)::numeric n FROM facility_service_capacity WHERE organization_id=$1`],trend:`SELECT to_char(date_trunc('day',observed_at),'YYYY-MM-DD') label,count(*)::int count FROM facility_service_capacity WHERE organization_id=$1 AND observed_at>=now()-interval '30 days' GROUP BY 1 ORDER BY 1`,breakdown:`SELECT status label,count(*)::int count FROM facility_service_capacity WHERE organization_id=$1 GROUP BY status ORDER BY count DESC`},
      'facility-resources':{kpis:[`SELECT count(*)::int n FROM facility_resource_status WHERE organization_id=$1`,`SELECT count(*)::int n FROM facility_resource_status WHERE organization_id=$1 AND status='critical'`,`SELECT count(*)::int n FROM facility_resource_status WHERE organization_id=$1 AND status='low'`,`SELECT count(*)::int n FROM facility_resource_status WHERE organization_id=$1 AND status='available'`],trend:`SELECT to_char(date_trunc('day',observed_at),'YYYY-MM-DD') label,count(*)::int count FROM facility_resource_status WHERE organization_id=$1 AND observed_at>=now()-interval '30 days' GROUP BY 1 ORDER BY 1`,breakdown:`SELECT status label,count(*)::int count FROM facility_resource_status WHERE organization_id=$1 GROUP BY status ORDER BY count DESC`},
      'facility-incidents':{kpis:[`SELECT count(*)::int n FROM facility_operational_incidents WHERE organization_id=$1`,`SELECT count(*)::int n FROM facility_operational_incidents WHERE organization_id=$1 AND severity='critical'`,`SELECT count(*)::int n FROM facility_operational_incidents WHERE organization_id=$1 AND status NOT IN ('resolved','closed')`,`SELECT count(*)::int n FROM facility_operational_incidents WHERE organization_id=$1 AND status IN ('resolved','closed')`],trend:`SELECT to_char(date_trunc('day',started_at),'YYYY-MM-DD') label,count(*)::int count FROM facility_operational_incidents WHERE organization_id=$1 AND started_at>=now()-interval '30 days' GROUP BY 1 ORDER BY 1`,breakdown:`SELECT severity label,count(*)::int count FROM facility_operational_incidents WHERE organization_id=$1 GROUP BY severity ORDER BY count DESC`},
      'facility-performance':{kpis:[`SELECT count(*)::int n FROM facility_performance_snapshots WHERE organization_id=$1`,`SELECT count(*)::int n FROM facility_performance_snapshots WHERE organization_id=$1 AND quality_status='reviewed'`,`SELECT count(DISTINCT indicator_code)::int n FROM facility_performance_snapshots WHERE organization_id=$1`,`SELECT count(DISTINCT facility_id)::int n FROM facility_performance_snapshots WHERE organization_id=$1`],trend:`SELECT to_char(period_end,'YYYY-MM-DD') label,count(*)::int count FROM facility_performance_snapshots WHERE organization_id=$1 AND period_end>=current_date-30 GROUP BY 1 ORDER BY 1`,breakdown:`SELECT indicator_name label,count(*)::int count FROM facility_performance_snapshots WHERE organization_id=$1 GROUP BY indicator_name ORDER BY count DESC LIMIT 12`},
      interoperability:{kpis:[`SELECT count(*)::int n FROM hie_connections WHERE organization_id=$1`,`SELECT count(*)::int n FROM hie_connections WHERE organization_id=$1 AND status='active'`,`SELECT count(*)::int n FROM hie_messages WHERE organization_id=$1`,`SELECT count(*)::int n FROM hie_messages WHERE organization_id=$1 AND status='failed'`],trend:`SELECT to_char(date_trunc('day',created_at),'YYYY-MM-DD') label,count(*)::int count FROM hie_messages WHERE organization_id=$1 AND created_at>=now()-interval '30 days' GROUP BY 1 ORDER BY 1`,breakdown:`SELECT status label,count(*)::int count FROM hie_messages WHERE organization_id=$1 GROUP BY status ORDER BY count DESC`},
      'health-connections':{kpis:[`SELECT count(*)::int n FROM hie_connections WHERE organization_id=$1`,`SELECT count(*)::int n FROM hie_connections WHERE organization_id=$1 AND status='active'`,`SELECT count(*)::int n FROM hie_messages WHERE organization_id=$1`,`SELECT count(*)::int n FROM hie_messages WHERE organization_id=$1 AND status='failed'`],trend:`SELECT to_char(date_trunc('day',created_at),'YYYY-MM-DD') label,count(*)::int count FROM hie_messages WHERE organization_id=$1 AND created_at>=now()-interval '30 days' GROUP BY 1 ORDER BY 1`,breakdown:`SELECT status label,count(*)::int count FROM hie_connections WHERE organization_id=$1 GROUP BY status ORDER BY count DESC`},
      audit:{kpis:[`SELECT count(*)::int n FROM audit_logs WHERE organization_id=$1`,`SELECT count(*)::int n FROM audit_logs WHERE organization_id=$1 AND created_at>=now()-interval '24 hours'`,`SELECT count(DISTINCT actor_user_id)::int n FROM audit_logs WHERE organization_id=$1`,`SELECT count(DISTINCT entity_type)::int n FROM audit_logs WHERE organization_id=$1`],trend:`SELECT to_char(date_trunc('day',created_at),'YYYY-MM-DD') label,count(*)::int count FROM audit_logs WHERE organization_id=$1 AND created_at>=now()-interval '30 days' GROUP BY 1 ORDER BY 1`,breakdown:`SELECT action label,count(*)::int count FROM audit_logs WHERE organization_id=$1 GROUP BY action ORDER BY count DESC LIMIT 12`},
      security:{kpis:[`SELECT count(*)::int n FROM security_events WHERE organization_id=$1`,`SELECT count(*)::int n FROM security_events WHERE organization_id=$1 AND severity IN ('high','critical')`,`SELECT count(*)::int n FROM security_events WHERE organization_id=$1 AND created_at>=now()-interval '24 hours'`,`SELECT count(*)::int n FROM ai_security_events WHERE organization_id=$1`],trend:`SELECT to_char(date_trunc('day',created_at),'YYYY-MM-DD') label,count(*)::int count FROM security_events WHERE organization_id=$1 AND created_at>=now()-interval '30 days' GROUP BY 1 ORDER BY 1`,breakdown:`SELECT severity label,count(*)::int count FROM security_events WHERE organization_id=$1 GROUP BY severity ORDER BY count DESC`},
      settings:{kpis:[`SELECT count(*)::int n FROM organization_settings WHERE organization_id=$1`,`SELECT count(DISTINCT category)::int n FROM organization_settings WHERE organization_id=$1`,`SELECT count(*)::int n FROM organization_settings WHERE organization_id=$1 AND updated_at>=now()-interval '30 days'`,`SELECT count(*)::int n FROM organization_settings WHERE organization_id=$1 AND value_type='json'`],trend:`SELECT to_char(date_trunc('day',created_at),'YYYY-MM-DD') label,count(*)::int count FROM organization_settings WHERE organization_id=$1 AND created_at>=now()-interval '30 days' GROUP BY 1 ORDER BY 1`,breakdown:`SELECT category label,count(*)::int count FROM organization_settings WHERE organization_id=$1 GROUP BY category ORDER BY count DESC`},
      terminology:{kpis:[`SELECT count(*)::int n FROM terminology_concepts WHERE organization_id=$1`,`SELECT count(DISTINCT system_uri)::int n FROM terminology_concepts WHERE organization_id=$1`,`SELECT count(*)::int n FROM terminology_concepts WHERE organization_id=$1 AND status='active'`,`SELECT count(*)::int n FROM terminology_concepts WHERE organization_id=$1 AND status<>'active'`],trend:`SELECT to_char(date_trunc('day',created_at),'YYYY-MM-DD') label,count(*)::int count FROM terminology_concepts WHERE organization_id=$1 AND created_at>=now()-interval '30 days' GROUP BY 1 ORDER BY 1`,breakdown:`SELECT system_uri label,count(*)::int count FROM terminology_concepts WHERE organization_id=$1 GROUP BY system_uri ORDER BY count DESC LIMIT 12`},
      guidelines:{kpis:[`SELECT count(*)::int n FROM clinical_guidelines WHERE organization_id=$1`,`SELECT count(*)::int n FROM clinical_guidelines WHERE organization_id=$1 AND status='active'`,`SELECT count(DISTINCT domain)::int n FROM clinical_guidelines WHERE organization_id=$1`,`SELECT count(*)::int n FROM clinical_guidelines WHERE organization_id=$1 AND effective_to IS NOT NULL AND effective_to<current_date`],trend:`SELECT to_char(date_trunc('day',created_at),'YYYY-MM-DD') label,count(*)::int count FROM clinical_guidelines WHERE organization_id=$1 AND created_at>=now()-interval '30 days' GROUP BY 1 ORDER BY 1`,breakdown:`SELECT domain label,count(*)::int count FROM clinical_guidelines WHERE organization_id=$1 GROUP BY domain ORDER BY count DESC`},
      'care-pathways':{kpis:[`SELECT count(*)::int n FROM care_pathways WHERE organization_id=$1`,`SELECT count(*)::int n FROM care_pathways WHERE organization_id=$1 AND status='active'`,`SELECT count(*)::int n FROM care_pathway_steps s JOIN care_pathways p ON p.id=s.pathway_id WHERE p.organization_id=$1`,`SELECT count(*)::int n FROM care_pathways WHERE organization_id=$1 AND status='draft'`],trend:`SELECT to_char(date_trunc('day',created_at),'YYYY-MM-DD') label,count(*)::int count FROM care_pathways WHERE organization_id=$1 AND created_at>=now()-interval '30 days' GROUP BY 1 ORDER BY 1`,breakdown:`SELECT domain label,count(*)::int count FROM care_pathways WHERE organization_id=$1 GROUP BY domain ORDER BY count DESC`},
      reporting:{kpis:[`SELECT count(*)::int n FROM reporting_submissions WHERE organization_id=$1`,`SELECT count(*)::int n FROM reporting_submissions WHERE organization_id=$1 AND status='submitted'`,`SELECT count(*)::int n FROM reporting_submissions WHERE organization_id=$1 AND status='accepted'`,`SELECT count(*)::int n FROM reporting_submissions WHERE organization_id=$1 AND status='rejected'`],trend:`SELECT to_char(date_trunc('day',created_at),'YYYY-MM-DD') label,count(*)::int count FROM reporting_submissions WHERE organization_id=$1 AND created_at>=now()-interval '30 days' GROUP BY 1 ORDER BY 1`,breakdown:`SELECT status label,count(*)::int count FROM reporting_submissions WHERE organization_id=$1 GROUP BY status ORDER BY count DESC`},
      'offline-sync':{kpis:[`SELECT count(*)::int n FROM offline_sync_queue WHERE organization_id=$1`,`SELECT count(*)::int n FROM offline_sync_queue WHERE organization_id=$1 AND status='pending'`,`SELECT count(*)::int n FROM offline_sync_queue WHERE organization_id=$1 AND status='conflict'`,`SELECT count(*)::int n FROM offline_sync_queue WHERE organization_id=$1 AND status='synced'`],trend:`SELECT to_char(date_trunc('day',created_at),'YYYY-MM-DD') label,count(*)::int count FROM offline_sync_queue WHERE organization_id=$1 AND created_at>=now()-interval '30 days' GROUP BY 1 ORDER BY 1`,breakdown:`SELECT status label,count(*)::int count FROM offline_sync_queue WHERE organization_id=$1 GROUP BY status ORDER BY count DESC`}
    };
    if(!map[module]) return {kpis:[],trend:[],breakdown:[]};
    const cfg=map[module]; const [ks,tr,br]=await Promise.all([Promise.all(cfg.kpis.map(q=>pool.query(q,[o]))),pool.query(cfg.trend,[o]),pool.query(cfg.breakdown,[o])]);
    const labels=module==='staff'?['Workforce','Active','On duty','Credentials expiring']:module==='facilities'?['Facilities','Active staff','Open incidents','Available capacity']:module==='facility-performance'?['Active encounters','Occupied beds','Pending laboratory','Pending imaging']:[];
    return {kpis:ks.map((x:any,i:number)=>({label:labels[i]||['Records','Active','Attention','Completed'][i],value:x.rows[0]?.n??0})),trend:tr.rows,breakdown:br.rows};
  }

  app.get('/api/phase89/:module',async(req:any,reply:any)=>{if(!pool)return noDb(reply);const m=String(req.params.module);if(!phaseModules.includes(m))return reply.code(404).send({error:'Module not found'});return {...await list(queries[m],[oid(req)]),module:m};});
  app.get('/api/phase89/:module/dashboard',async(req:any,reply:any)=>{if(!pool)return noDb(reply);const m=String(req.params.module);if(!phaseModules.includes(m))return reply.code(404).send({error:'Module not found'});return {data:await dashboard(req,m)};});

  app.post('/api/phase89/staff',async(req:any,reply:any)=>{if(!pool)return noDb(reply);requireAuthorizedWrite(req);const b=z.object({userId:id,facilityId:id.optional(),cadre:z.string().min(1),profession:z.string().min(1),registrationSystem:z.string().optional(),registrationNumber:z.string().optional(),specialty:z.string().optional(),department:z.string().optional(),role:z.string().optional(),shift:z.string().optional(),availabilityStatus:z.string().optional(),leaveStatus:z.string().optional(),workload:z.number().optional(),licenseExpiry:z.string().optional(),credentials:json.optional()}).parse(req.body||{});const r=await pool.query(`INSERT INTO health_worker_profiles(organization_id,user_id,facility_id,cadre,profession,registration_system,registration_number,specialty,department,role,shift,availability_status,leave_status,workload,license_expiry,credentials) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16 WHERE EXISTS(SELECT 1 FROM users WHERE id=$2) RETURNING id`,[oid(req),b.userId,b.facilityId||null,b.cadre,b.profession,b.registrationSystem||null,b.registrationNumber||null,b.specialty||null,b.department||null,b.role||null,b.shift||null,b.availabilityStatus||null,b.leaveStatus||null,b.workload??null,b.licenseExpiry||null,JSON.stringify(b.credentials||{})]);if(!r.rowCount)return reply.code(404).send({error:'User not found'});return reply.code(201).send({id:r.rows[0].id});});
  app.post('/api/phase89/facilities',async(req:any,reply:any)=>{if(!pool)return noDb(reply);requireAuthorizedWrite(req);const b=z.object({name:z.string().min(1),type:z.string().min(1),timezone:z.string().min(1).default('Africa/Kampala')}).parse(req.body||{});const r=await pool.query(`INSERT INTO facilities(organization_id,name,type,timezone) VALUES($1,$2,$3,$4) RETURNING *`,[oid(req),b.name,b.type,b.timezone]);return reply.code(201).send(r.rows[0]);});
  app.post('/api/phase89/facility-capacity',async(req:any,reply:any)=>{if(!pool)return noDb(reply);requireAuthorizedWrite(req);const b=z.object({facilityId:id,serviceCode:z.string().min(1),serviceName:z.string().min(1),status:z.enum(['available','limited','unavailable','planned']).default('available'),capacityTotal:z.number().int().nonnegative().optional(),capacityAvailable:z.number().int().nonnegative().optional(),waitMinutes:z.number().int().nonnegative().optional(),operatingHours:json.optional(),metadata:json.optional()}).parse(req.body||{});const r=await pool.query(`INSERT INTO facility_service_capacity(organization_id,facility_id,service_code,service_name,status,capacity_total,capacity_available,wait_minutes,operating_hours,metadata) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10 WHERE EXISTS(SELECT 1 FROM facilities WHERE id=$2 AND organization_id=$1) RETURNING *`,[oid(req),b.facilityId,b.serviceCode,b.serviceName,b.status,b.capacityTotal??null,b.capacityAvailable??null,b.waitMinutes??null,JSON.stringify(b.operatingHours||{}),JSON.stringify(b.metadata||{})]);if(!r.rowCount)return reply.code(404).send({error:'Facility not found'});return reply.code(201).send(r.rows[0]);});
  app.post('/api/phase89/facility-resources',async(req:any,reply:any)=>{if(!pool)return noDb(reply);requireAuthorizedWrite(req);const b=z.object({facilityId:id,resourceType:z.string().min(1),resourceName:z.string().min(1),status:z.enum(['available','low','critical','unavailable','unknown']).default('available'),quantity:z.number().nonnegative().optional(),unit:z.string().optional(),threshold:z.number().nonnegative().optional(),maintenanceStatus:z.string().optional(),maintenanceDueAt:z.string().optional(),notes:json.optional()}).parse(req.body||{});const r=await pool.query(`INSERT INTO facility_resource_status(organization_id,facility_id,resource_type,resource_name,status,quantity,unit,threshold,maintenance_status,maintenance_due_at,notes) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11 WHERE EXISTS(SELECT 1 FROM facilities WHERE id=$2 AND organization_id=$1) RETURNING *`,[oid(req),b.facilityId,b.resourceType,b.resourceName,b.status,b.quantity??null,b.unit||null,b.threshold??null,b.maintenanceStatus||null,b.maintenanceDueAt||null,JSON.stringify(b.notes||{})]);if(!r.rowCount)return reply.code(404).send({error:'Facility not found'});return reply.code(201).send(r.rows[0]);});
  app.post('/api/phase89/facility-incidents',async(req:any,reply:any)=>{if(!pool)return noDb(reply);requireAuthorizedWrite(req);const b=z.object({facilityId:id,districtId:id.optional(),incidentType:z.string().min(1),severity:z.enum(['low','moderate','high','critical']).default('moderate'),title:z.string().min(1),description:z.string().optional(),responseOwner:id.optional(),impact:json.optional()}).parse(req.body||{});const r=await pool.query(`INSERT INTO facility_operational_incidents(organization_id,facility_id,district_id,incident_type,severity,title,description,response_owner,impact,created_by) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10 WHERE EXISTS(SELECT 1 FROM facilities WHERE id=$2 AND organization_id=$1) RETURNING *`,[oid(req),b.facilityId,b.districtId||null,b.incidentType,b.severity,b.title,b.description||null,b.responseOwner||null,JSON.stringify(b.impact||{}),dbUserId(req)]);if(!r.rowCount)return reply.code(404).send({error:'Facility not found'});return reply.code(201).send(r.rows[0]);});
  app.post('/api/phase89/facility-incidents/:id/action',async(req:any,reply:any)=>{if(!pool)return noDb(reply);requireAuthorizedWrite(req);const b=z.object({status:z.enum(['open','acknowledged','mitigating','resolved','closed']),resolutionNote:z.string().optional()}).parse(req.body||{});const r=await pool.query(`UPDATE facility_operational_incidents SET status=$1,resolved_at=CASE WHEN $1 IN ('resolved','closed') THEN COALESCE(resolved_at,now()) ELSE NULL END,impact=CASE WHEN $2 IS NULL THEN impact ELSE impact || jsonb_build_object('resolutionNote',$2) END,updated_at=now() WHERE id=$3 AND organization_id=$4 RETURNING *`,[b.status,b.resolutionNote||null,req.params.id,oid(req)]);if(!r.rowCount)return reply.code(404).send({error:'Incident not found'});return reply.send(r.rows[0]);});
  app.post('/api/phase89/facility-performance',async(req:any,reply:any)=>{if(!pool)return noDb(reply);requireAuthorizedWrite(req);const b=z.object({facilityId:id,districtId:id.optional(),periodStart:z.string(),periodEnd:z.string(),indicatorCode:z.string().min(1),indicatorName:z.string().min(1),numerator:z.number().optional(),denominator:z.number().optional(),valueNumeric:z.number().optional(),unit:z.string().optional(),qualityStatus:z.string().default('unreviewed'),dimensions:json.optional(),source:z.string().optional()}).parse(req.body||{});const r=await pool.query(`INSERT INTO facility_performance_snapshots(organization_id,facility_id,district_id,period_start,period_end,indicator_code,indicator_name,numerator,denominator,value_numeric,unit,quality_status,dimensions,source) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14 WHERE EXISTS(SELECT 1 FROM facilities WHERE id=$2 AND organization_id=$1) RETURNING *`,[oid(req),b.facilityId,b.districtId||null,b.periodStart,b.periodEnd,b.indicatorCode,b.indicatorName,b.numerator??null,b.denominator??null,b.valueNumeric??null,b.unit||null,b.qualityStatus,JSON.stringify(b.dimensions||{}),b.source||null]);if(!r.rowCount)return reply.code(404).send({error:'Facility not found'});return reply.code(201).send(r.rows[0]);});

  app.post('/api/phase89/health-connections',async(req:any,reply:any)=>{if(!pool)return noDb(reply);requireAuthorizedWrite(req);const b=z.object({name:z.string().min(1),jurisdiction:z.string().default('UG'),protocol:z.string().min(1),baseUrl:z.string().url().optional(),status:z.enum(['disabled','active','error']).default('disabled'),capabilities:json.optional(),credentialRef:z.string().optional()}).parse(req.body||{});const r=await pool.query(`INSERT INTO hie_connections(organization_id,name,jurisdiction,protocol,base_url,status,capabilities,credential_ref) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[oid(req),b.name,b.jurisdiction,b.protocol,b.baseUrl||null,b.status,JSON.stringify(b.capabilities||{}),b.credentialRef||null]);return reply.code(201).send(r.rows[0]);});
  app.post('/api/phase89/interoperability',async(req:any,reply:any)=>{if(!pool)return noDb(reply);requireAuthorizedWrite(req);const b=z.object({system:z.string().min(1),standard:z.string().min(1),endpoint:z.string().url().optional(),direction:z.enum(['inbound','outbound','bidirectional']).default('bidirectional'),version:z.string().optional(),status:z.enum(['disabled','active','error']).default('disabled')}).parse(req.body||{});const r=await pool.query(`INSERT INTO hie_connections(organization_id,name,jurisdiction,protocol,base_url,status,capabilities) VALUES($1,$2,'UG',$3,$4,$5,$6,$7) RETURNING id,name AS system,protocol AS standard,base_url AS endpoint,status,capabilities`,[oid(req),b.system,b.standard,b.endpoint||null,b.status,JSON.stringify({direction:b.direction,version:b.version||null})]);return reply.code(201).send(r.rows[0]);});
  app.post('/api/phase89/health-connections/:id/action',async(req:any,reply:any)=>{if(!pool)return noDb(reply);requireAuthorizedWrite(req);const b=z.object({status:z.enum(['disabled','active','error'])}).parse(req.body||{});const r=await pool.query(`UPDATE hie_connections SET status=$1,updated_at=now() WHERE id=$2 AND organization_id=$3 RETURNING *`,[b.status,req.params.id,oid(req)]);if(!r.rowCount)return reply.code(404).send({error:'Connection not found'});return reply.send(r.rows[0]);});
  app.post('/api/phase89/interoperability/:id/action',async(req:any,reply:any)=>{if(!pool)return noDb(reply);requireAuthorizedWrite(req);const b=z.object({status:z.enum(['disabled','active','error'])}).parse(req.body||{});const r=await pool.query(`UPDATE hie_connections SET status=$1,updated_at=now() WHERE id=$2 AND organization_id=$3 RETURNING *`,[b.status,req.params.id,oid(req)]);if(!r.rowCount)return reply.code(404).send({error:'Connection not found'});return reply.send(r.rows[0]);});
  app.post('/api/phase89/interoperability/:id/message',async(req:any,reply:any)=>{if(!pool)return noDb(reply);requireAuthorizedWrite(req);const b=z.object({direction:z.enum(['outbound','inbound']),resourceType:z.string().optional(),payload:json,status:z.enum(['queued','processing','sent','failed','received']).default('queued')}).parse(req.body||{});const r=await pool.query(`INSERT INTO hie_messages(organization_id,connection_id,direction,resource_type,payload,status) SELECT $1,$2,$3,$4,$5,$6 WHERE EXISTS(SELECT 1 FROM hie_connections WHERE id=$2 AND organization_id=$1) RETURNING *`,[oid(req),req.params.id,b.direction,b.resourceType||null,JSON.stringify(b.payload),b.status]);if(!r.rowCount)return reply.code(404).send({error:'Connection not found'});return reply.code(201).send(r.rows[0]);});

  app.post('/api/phase89/settings',async(req:any,reply:any)=>{if(!pool)return noDb(reply);requireAuthorizedWrite(req);const b=z.object({category:z.string().min(1),name:z.string().min(1),value:z.string(),valueType:z.enum(['text','number','boolean','json']).default('text'),description:z.string().optional()}).parse(req.body||{});const r=await pool.query(`INSERT INTO organization_settings(organization_id,category,name,value,value_type,description,updated_at) VALUES($1,$2,$3,$4,$5,$6,now()) ON CONFLICT(organization_id,category,name) DO UPDATE SET value=EXCLUDED.value,value_type=EXCLUDED.value_type,description=EXCLUDED.description,updated_at=now() RETURNING *`,[oid(req),b.category,b.name,b.value,b.valueType,b.description||null]);return reply.code(201).send(r.rows[0]);});
  app.post('/api/phase89/terminology',async(req:any,reply:any)=>{if(!pool)return noDb(reply);requireAuthorizedWrite(req);const b=z.object({systemUri:z.string().min(2),code:z.string().min(1),display:z.string().min(1),version:z.string().optional(),status:z.string().default('active'),source:z.string().optional(),sourceUrl:z.string().url().optional(),properties:json.optional()}).parse(req.body||{});const r=await pool.query(`INSERT INTO terminology_concepts(organization_id,system_uri,code,display,version,status,source,source_url,properties) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[oid(req),b.systemUri,b.code,b.display,b.version||null,b.status,b.source||null,b.sourceUrl||null,JSON.stringify(b.properties||{})]);return reply.code(201).send(r.rows[0]);});
  app.post('/api/phase89/care-pathways',async(req:any,reply:any)=>{if(!pool)return noDb(reply);requireAuthorizedWrite(req);const b=z.object({name:z.string().min(1),code:z.string().min(1),domain:z.string().min(1),jurisdiction:z.string().default('UG'),status:z.enum(['draft','active','retired']).default('draft'),version:z.string().min(1),sourceGuidelineId:id.optional(),metadata:json.optional()}).parse(req.body||{});const r=await pool.query(`INSERT INTO care_pathways(organization_id,name,code,domain,jurisdiction,status,version,source_guideline_id,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[oid(req),b.name,b.code,b.domain,b.jurisdiction,b.status,b.version,b.sourceGuidelineId||null,JSON.stringify(b.metadata||{})]);return reply.code(201).send(r.rows[0]);});
  app.post('/api/phase89/reporting',async(req:any,reply:any)=>{if(!pool)return noDb(reply);requireAuthorizedWrite(req);const b=z.object({reportingSystem:z.string().min(1),periodStart:z.string(),periodEnd:z.string(),payload:json,status:z.enum(['draft','ready','submitted','accepted','rejected']).default('draft'),externalReference:z.string().optional()}).parse(req.body||{});const r=await pool.query(`INSERT INTO reporting_submissions(organization_id,reporting_system,period_start,period_end,payload,status,external_reference,created_by,submitted_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,CASE WHEN $6='submitted' THEN now() ELSE NULL END) RETURNING *`,[oid(req),b.reportingSystem,b.periodStart,b.periodEnd,JSON.stringify(b.payload),b.status,b.externalReference||null,dbUserId(req)]);return reply.code(201).send(r.rows[0]);});
  app.post('/api/phase89/reporting/:id/action',async(req:any,reply:any)=>{if(!pool)return noDb(reply);requireAuthorizedWrite(req);const b=z.object({status:z.enum(['draft','ready','submitted','accepted','rejected']),externalReference:z.string().optional(),error:z.string().optional()}).parse(req.body||{});const r=await pool.query(`UPDATE reporting_submissions SET status=$1,external_reference=COALESCE($2,external_reference),error=$3,submitted_at=CASE WHEN $1='submitted' THEN COALESCE(submitted_at,now()) ELSE submitted_at END WHERE id=$4 AND organization_id=$5 RETURNING *`,[b.status,b.externalReference||null,b.error||null,req.params.id,oid(req)]);if(!r.rowCount)return reply.code(404).send({error:'Reporting submission not found'});return reply.send(r.rows[0]);});
  app.post('/api/phase89/offline-sync',async(req:any,reply:any)=>{if(!pool)return noDb(reply);requireAuthorizedWrite(req);const b=z.object({deviceId:z.string().min(1),operationId:z.string().min(1),resourceType:z.string().min(1),resourceId:z.string().optional(),operation:z.enum(['create','update','delete']),payload:json,baseVersion:z.string().optional()}).parse(req.body||{});const r=await pool.query(`INSERT INTO offline_sync_queue(organization_id,device_id,user_id,operation_id,resource_type,resource_id,operation,payload,base_version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(organization_id,operation_id) DO NOTHING RETURNING *`,[oid(req),b.deviceId,dbUserId(req),b.operationId,b.resourceType,b.resourceId||null,b.operation,JSON.stringify(b.payload),b.baseVersion||null]);return reply.code(202).send(r.rows[0]||{status:'duplicate',operationId:b.operationId});});
  app.post('/api/phase89/offline-sync/:id/action',async(req:any,reply:any)=>{if(!pool)return noDb(reply);requireAuthorizedWrite(req);const b=z.object({status:z.enum(['pending','processing','synced','failed','conflict']),conflict:json.optional()}).parse(req.body||{});const r=await pool.query(`UPDATE offline_sync_queue SET status=$1,conflict=$2,synced_at=CASE WHEN $1='synced' THEN COALESCE(synced_at,now()) ELSE synced_at END WHERE id=$3 AND organization_id=$4 RETURNING *`,[b.status,b.conflict?JSON.stringify(b.conflict):null,req.params.id,oid(req)]);if(!r.rowCount)return reply.code(404).send({error:'Sync item not found'});return reply.send(r.rows[0]);});
}
