import { z } from 'zod';
import type { FastifyInstance } from 'fastify';
import type { Pool } from 'pg';

type Row = Record<string, any>;
type Ctx = { dbOrganizationId:(req:any)=>string|null; dbUserId:(req:any)=>string|null; requireAuthorizedWrite:(req:any)=>void; dbAudit:(client:any,req:any,action:string,entityType:string,entityId:string,metadata?:Row)=>Promise<void>; queueEvent:(client:any,req:any,type:string,payload:Row)=>Promise<void>; clinicalEventTypes:any };

export function registerWorkstream2DomainRoutes(app:FastifyInstance,pool:Pool|null,ctx:Ctx){
  const oid=(req:any)=>ctx.dbOrganizationId(req);
  const write=(req:any)=>ctx.requireAuthorizedWrite(req);
  const requireDb=(reply:any)=>{if(!pool){reply.code(501).send({error:'PostgreSQL required'});return false;}return true;};

  app.get('/api/domains/finance/overview',async(req:any,reply:any)=>{
    if(!requireDb(reply))return; const organizationId=oid(req); if(!organizationId)return reply.code(400).send({error:'Organization context is required'});
    const [summary,recent,recon]=await Promise.all([
      pool!.query(`SELECT count(*)::int AS invoice_count,count(*) FILTER(WHERE status='paid')::int AS paid_count,count(*) FILTER(WHERE status<>'paid')::int AS open_count,COALESCE(sum(total),0)::numeric AS billed FROM invoices WHERE organization_id=$1`,[organizationId]),
      pool!.query(`SELECT i.id,i.patient_id AS "patientId",p.patient_number AS "patientNumber",i.total,i.currency,i.status,i.created_at AS "createdAt",COALESCE((SELECT sum(amount) FROM payments py WHERE py.invoice_id=i.id AND py.status='completed'),0)::numeric AS paid FROM invoices i LEFT JOIN patients p ON p.id=i.patient_id WHERE i.organization_id=$1 ORDER BY i.created_at DESC LIMIT 100`,[organizationId]),
      pool!.query(`SELECT fr.*,p.patient_number AS "patientNumber",c.status AS "claimStatus" FROM finance_reconciliations fr JOIN invoices i ON i.id=fr.invoice_id LEFT JOIN patients p ON p.id=i.patient_id LEFT JOIN claims c ON c.id=fr.claim_id WHERE fr.organization_id=$1 ORDER BY fr.created_at DESC LIMIT 100`,[organizationId])
    ]); return {summary:summary.rows[0],invoices:recent.rows,reconciliations:recon.rows};
  });

  app.get('/api/domains/insurance/overview',async(req:any,reply:any)=>{
    if(!requireDb(reply))return; const organizationId=oid(req); if(!organizationId)return reply.code(400).send({error:'Organization context is required'});
    const [providers,policies,eligibility,authorizations]=await Promise.all([
      pool!.query(`SELECT id,name,status,contact FROM insurance_providers WHERE organization_id=$1 ORDER BY name`,[organizationId]),
      pool!.query(`SELECT ip.id,ip.patient_id AS "patientId",p.patient_number AS "patientNumber",ip.provider_id AS "providerId",pr.name AS "providerName",ip.policy_number AS "policyNumber",ip.member_number AS "memberNumber",ip.status,ip.effective_from AS "effectiveFrom",ip.effective_to AS "effectiveTo",ip.copay_percent AS "copayPercent",ip.annual_limit AS "annualLimit",ip.coverage FROM insurance_policies ip JOIN patients p ON p.id=ip.patient_id JOIN insurance_providers pr ON pr.id=ip.provider_id WHERE ip.organization_id=$1 ORDER BY ip.id DESC LIMIT 500`,[organizationId]),
      pool!.query(`SELECT e.*,p.patient_number AS "patientNumber",ip.policy_number AS "policyNumber" FROM insurance_eligibility_checks e JOIN patients p ON p.id=e.patient_id JOIN insurance_policies ip ON ip.id=e.policy_id WHERE e.organization_id=$1 ORDER BY e.checked_at DESC LIMIT 100`,[organizationId]),
      pool!.query(`SELECT a.*,p.patient_number AS "patientNumber",ip.policy_number AS "policyNumber" FROM insurance_authorizations a JOIN patients p ON p.id=a.patient_id JOIN insurance_policies ip ON ip.id=a.policy_id WHERE a.organization_id=$1 ORDER BY a.requested_at DESC LIMIT 100`,[organizationId])
    ]); return {providers:providers.rows,policies:policies.rows,eligibility:eligibility.rows,authorizations:authorizations.rows};
  });

  app.post('/api/domains/insurance/eligibility',async(req:any,reply:any)=>{
    write(req); if(!requireDb(reply))return; const b=z.object({policyId:z.string().uuid(),patientId:z.string().uuid(),encounterId:z.string().uuid().optional(),serviceCode:z.string().optional(),status:z.enum(['eligible','ineligible','pending']).default('eligible'),expiresAt:z.string().optional(),response:z.record(z.any()).default({})}).parse(req.body||{}); const organizationId=oid(req)!;
    const r=await pool!.query(`INSERT INTO insurance_eligibility_checks(organization_id,policy_id,patient_id,encounter_id,service_code,status,expires_at,response,created_by) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9 WHERE EXISTS(SELECT 1 FROM insurance_policies WHERE id=$2 AND patient_id=$3 AND organization_id=$1) RETURNING *`,[organizationId,b.policyId,b.patientId,b.encounterId||null,b.serviceCode||null,b.status,b.expiresAt||null,JSON.stringify(b.response),ctx.dbUserId(req)]); if(!r.rowCount)return reply.code(409).send({error:'Policy, patient and organization relationship is invalid'}); return reply.code(201).send(r.rows[0]);
  });

  app.post('/api/domains/insurance/authorizations',async(req:any,reply:any)=>{
    write(req); if(!requireDb(reply))return; const b=z.object({policyId:z.string().uuid(),patientId:z.string().uuid(),encounterId:z.string().uuid().optional(),serviceCode:z.string().min(1),requestedAmount:z.number().nonnegative(),status:z.enum(['requested','approved','rejected']).default('requested'),approvedAmount:z.number().nonnegative().optional(),authorizationNumber:z.string().optional(),response:z.record(z.any()).default({})}).parse(req.body||{}); const organizationId=oid(req)!;
    const r=await pool!.query(`INSERT INTO insurance_authorizations(organization_id,policy_id,patient_id,encounter_id,service_code,requested_amount,approved_amount,status,authorization_number,decided_at,response,created_by) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,CASE WHEN $8 IN ('approved','rejected') THEN now() ELSE NULL END,$10,$11 WHERE EXISTS(SELECT 1 FROM insurance_policies WHERE id=$2 AND patient_id=$3 AND organization_id=$1) RETURNING *`,[organizationId,b.policyId,b.patientId,b.encounterId||null,b.serviceCode,b.requestedAmount,b.approvedAmount??null,b.status,b.authorizationNumber||null,JSON.stringify(b.response),ctx.dbUserId(req)]); if(!r.rowCount)return reply.code(409).send({error:'Policy, patient and organization relationship is invalid'}); return reply.code(201).send(r.rows[0]);
  });

  app.get('/api/domains/claims',async(req:any,reply:any)=>{
    if(!requireDb(reply))return; const organizationId=oid(req); if(!organizationId)return reply.code(400).send({error:'Organization context is required'}); const r=await pool!.query(`SELECT c.*,p.patient_number AS "patientNumber",i.total AS "invoiceTotal",i.currency,ip.policy_number AS "policyNumber",pr.name AS "providerName",COALESCE((SELECT jsonb_agg(ci ORDER BY ci.created_at) FROM claim_items ci WHERE ci.claim_id=c.id),'[]'::jsonb) AS items,COALESCE((SELECT jsonb_agg(cr ORDER BY cr.received_at DESC) FROM claim_responses cr WHERE cr.claim_id=c.id),'[]'::jsonb) AS responses FROM claims c LEFT JOIN patients p ON p.id=c.patient_id LEFT JOIN invoices i ON i.id=c.invoice_id LEFT JOIN insurance_policies ip ON ip.id=c.policy_id LEFT JOIN insurance_providers pr ON pr.id=ip.provider_id WHERE (p.organization_id=$1 OR i.organization_id=$1) ORDER BY c.submitted_at DESC NULLS LAST,c.id DESC LIMIT 500`,[organizationId]); return {data:r.rows,count:r.rowCount};
  });

  app.post('/api/domains/claims/:id/respond',async(req:any,reply:any)=>{
    write(req); if(!requireDb(reply))return; const b=z.object({status:z.enum(['approved','rejected','partially-approved']),approvedAmount:z.number().nonnegative().optional(),rejectedAmount:z.number().nonnegative().optional(),payerReference:z.string().optional(),reason:z.string().optional(),response:z.record(z.any()).default({})}).parse(req.body||{}); const organizationId=oid(req)!; const client=await pool!.connect(); try{await client.query('BEGIN'); const c=await client.query(`SELECT c.id,c.invoice_id AS "invoiceId",c.policy_id AS "policyId",c.patient_id AS "patientId",COALESCE(c.amount,i.total) AS amount FROM claims c LEFT JOIN invoices i ON i.id=c.invoice_id JOIN patients p ON p.id=c.patient_id WHERE c.id=$1 AND p.organization_id=$2 FOR UPDATE`,[req.params.id,organizationId]); if(!c.rowCount){await client.query('ROLLBACK');return reply.code(404).send({error:'Claim not found'});} const approved=b.status==='approved'?Number(b.approvedAmount??c.rows[0].amount):b.status==='partially-approved'?Number(b.approvedAmount??0):0; const response=await client.query(`INSERT INTO claim_responses(claim_id,response_type,status,payer_reference,approved_amount,rejected_amount,reason,payload,created_by) VALUES($1,'payer-response',$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[req.params.id,b.status,b.payerReference||null,approved,Number(b.rejectedAmount??Math.max(Number(c.rows[0].amount)-approved,0)),b.reason||null,JSON.stringify(b.response),ctx.dbUserId(req)]); await client.query(`UPDATE claims SET status=$1,responded_at=now(),payer_reference=COALESCE($2,payer_reference),rejection_reason=$3,coverage_amount=$4,patient_responsibility=GREATEST(COALESCE(amount,0)-$4,0) WHERE id=$5`,[b.status,b.payerReference||null,b.reason||null,approved,req.params.id]); const rec=await client.query(`INSERT INTO finance_reconciliations(organization_id,invoice_id,claim_id,invoice_amount,claimed_amount,approved_amount,patient_responsibility,status,created_by) SELECT $1,c.invoice_id,c.id,COALESCE(i.total,0),COALESCE(c.amount,i.total),$2,GREATEST(COALESCE(c.amount,i.total)-$2,0),CASE WHEN $3='approved' THEN 'awaiting-settlement' ELSE 'exception' END,$4 FROM claims c LEFT JOIN invoices i ON i.id=c.invoice_id WHERE c.id=$5 ON CONFLICT(invoice_id,claim_id,payment_id) DO NOTHING RETURNING id`,[organizationId,c.rows[0].invoiceId,approved,b.status,ctx.dbUserId(req),req.params.id]); await ctx.dbAudit(client,req,'CLAIM_RESPONSE','claim',req.params.id,{status:b.status,approvedAmount:approved}); await ctx.queueEvent(client,req,'insurance.claim.responded',{claimId:req.params.id,patientId:c.rows[0].patientId,status:b.status,approvedAmount:approved,reconciliationId:rec.rows[0]?.id||null}); await client.query('COMMIT'); return {claimId:req.params.id,status:b.status,response:response.rows[0],reconciliationId:rec.rows[0]?.id||null}; }catch(e){await client.query('ROLLBACK');throw e}finally{client.release();}
  });

  app.get('/api/domains/inventory/overview',async(req:any,reply:any)=>{
    if(!requireDb(reply))return; const organizationId=oid(req); if(!organizationId)return reply.code(400).send({error:'Organization context is required'}); const [items,movements,low]=await Promise.all([
      pool!.query(`SELECT ii.*,COALESCE((SELECT sum(ib.quantity) FROM inventory_batches ib WHERE ib.item_id=ii.id),0)::numeric AS "onHand",COALESCE((SELECT min(ib.expiry_date) FROM inventory_batches ib WHERE ib.item_id=ii.id AND ib.quantity>0),NULL) AS "nearestExpiry" FROM inventory_items ii WHERE ii.organization_id=$1 ORDER BY ii.name`,[organizationId]),
      pool!.query(`SELECT sm.*,ii.name AS "itemName",ii.sku,ib.batch_number AS "batchNumber" FROM stock_movements sm JOIN inventory_items ii ON ii.id=sm.item_id LEFT JOIN inventory_batches ib ON ib.id=sm.batch_id WHERE ii.organization_id=$1 ORDER BY sm.created_at DESC LIMIT 200`,[organizationId]),
      pool!.query(`SELECT ii.id,ii.name,ii.sku,ii.reorder_level,COALESCE(sum(ib.quantity),0)::numeric AS "onHand" FROM inventory_items ii LEFT JOIN inventory_batches ib ON ib.item_id=ii.id WHERE ii.organization_id=$1 GROUP BY ii.id HAVING COALESCE(sum(ib.quantity),0)<=ii.reorder_level ORDER BY "onHand"`,[organizationId])
    ]); return {items:items.rows,movements:movements.rows,lowStock:low.rows};
  });

  app.post('/api/domains/inventory/receive',async(req:any,reply:any)=>{
    write(req); if(!requireDb(reply))return; const b=z.object({itemId:z.string().uuid(),batchNumber:z.string().min(1),quantity:z.number().positive(),expiryDate:z.string().optional(),location:z.string().optional(),referenceType:z.string().default('purchase_order'),referenceId:z.string().uuid().optional()}).parse(req.body||{}); const organizationId=oid(req)!; const client=await pool!.connect(); try{await client.query('BEGIN'); const item=await client.query(`SELECT id,name,sku FROM inventory_items WHERE id=$1 AND organization_id=$2 FOR UPDATE`,[b.itemId,organizationId]); if(!item.rowCount){await client.query('ROLLBACK');return reply.code(404).send({error:'Inventory item not found'});} const batch=await client.query(`INSERT INTO inventory_batches(item_id,batch_number,expiry_date,quantity,location) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING RETURNING *`,[b.itemId,b.batchNumber,b.expiryDate||null,b.quantity,b.location||null]); let batchRow=batch.rows[0]; if(!batchRow){const existing=await client.query(`SELECT * FROM inventory_batches WHERE item_id=$1 AND batch_number=$2 FOR UPDATE`,[b.itemId,b.batchNumber]); if(!existing.rowCount){await client.query('ROLLBACK');return reply.code(409).send({error:'Unable to create inventory batch'});} await client.query(`UPDATE inventory_batches SET quantity=quantity+$1 WHERE id=$2`,[b.quantity,existing.rows[0].id]); batchRow=(await client.query(`SELECT * FROM inventory_batches WHERE id=$1`,[existing.rows[0].id])).rows[0];} const movement=await client.query(`INSERT INTO stock_movements(item_id,batch_id,movement_type,quantity,reference_type,reference_id,created_by) VALUES($1,$2,'receipt',$3,$4,$5,$6) RETURNING *`,[b.itemId,batchRow.id,b.quantity,b.referenceType,b.referenceId||null,ctx.dbUserId(req)]); await ctx.dbAudit(client,req,'RECEIVE','inventory_batch',batchRow.id,{itemId:b.itemId,quantity:b.quantity}); await ctx.queueEvent(client,req,'inventory.stock.received',{itemId:b.itemId,batchId:batchRow.id,quantity:b.quantity,referenceId:b.referenceId||null}); await client.query('COMMIT'); return reply.code(201).send({item:item.rows[0],batch:batchRow,movement:movement.rows[0]}); }catch(e){await client.query('ROLLBACK');throw e}finally{client.release();}
  });

  app.get('/api/domains/procurement/overview',async(req:any,reply:any)=>{
    if(!requireDb(reply))return; const organizationId=oid(req); if(!organizationId)return reply.code(400).send({error:'Organization context is required'}); const [requests,orders,suppliers]=await Promise.all([
      pool!.query(`SELECT pr.*,s.name AS "supplierName" FROM procurement_requests pr LEFT JOIN suppliers s ON s.id=pr.supplier_id WHERE pr.organization_id=$1 ORDER BY pr.requested_at DESC LIMIT 200`,[organizationId]),
      pool!.query(`SELECT po.*,s.name AS "supplierName",pr.description AS "requestDescription",COALESCE((SELECT jsonb_agg(poi ORDER BY poi.created_at) FROM purchase_order_items poi WHERE poi.purchase_order_id=po.id),'[]'::jsonb) AS items FROM purchase_orders po LEFT JOIN suppliers s ON s.id=po.supplier_id LEFT JOIN procurement_requests pr ON pr.id=po.procurement_request_id WHERE po.organization_id=$1 ORDER BY po.created_at DESC LIMIT 200`,[organizationId]),
      pool!.query(`SELECT s.*,COALESCE((SELECT count(*) FROM purchase_orders po WHERE po.supplier_id=s.id),0)::int AS "orderCount",COALESCE((SELECT sum(poi.total) FROM purchase_order_items poi JOIN purchase_orders po ON po.id=poi.purchase_order_id WHERE po.supplier_id=s.id),0)::numeric AS "orderValue" FROM suppliers s WHERE s.organization_id=$1 ORDER BY s.name`,[organizationId])
    ]); return {requests:requests.rows,orders:orders.rows,suppliers:suppliers.rows};
  });

  app.post('/api/domains/procurement/:id/approve',async(req:any,reply:any)=>{
    write(req); if(!requireDb(reply))return; const organizationId=oid(req)!; const client=await pool!.connect(); try{await client.query('BEGIN'); const r=await client.query(`UPDATE procurement_requests SET status='approved',approved_at=COALESCE(approved_at,now()) WHERE id=$1 AND organization_id=$2 AND status IN ('requested','pending') RETURNING *`,[req.params.id,organizationId]); if(!r.rowCount){await client.query('ROLLBACK');return reply.code(404).send({error:'Procurement request not found or already approved'});} await ctx.dbAudit(client,req,'APPROVE','procurement_request',req.params.id,{}); await ctx.queueEvent(client,req,'procurement.request.approved',{procurementRequestId:req.params.id,supplierId:r.rows[0].supplier_id,quantity:r.rows[0].quantity}); await client.query('COMMIT'); return r.rows[0];}catch(e){await client.query('ROLLBACK');throw e}finally{client.release();}
  });

  app.post('/api/domains/procurement/:id/purchase-order',async(req:any,reply:any)=>{
    write(req); if(!requireDb(reply))return; const b=z.object({items:z.array(z.object({inventoryItemId:z.string().uuid().optional(),description:z.string().min(1),quantity:z.number().positive(),unitPrice:z.number().nonnegative()})).min(1)}).parse(req.body||{}); const organizationId=oid(req)!; const client=await pool!.connect(); try{await client.query('BEGIN'); const pr=await client.query(`SELECT * FROM procurement_requests WHERE id=$1 AND organization_id=$2 AND status='approved' FOR UPDATE`,[req.params.id,organizationId]); if(!pr.rowCount){await client.query('ROLLBACK');return reply.code(409).send({error:'Only an approved procurement request can become a purchase order'});} const po=await client.query(`INSERT INTO purchase_orders(organization_id,supplier_id,status,procurement_request_id,issued_at,notes) VALUES($1,$2,'issued',$3,now(),$4) RETURNING *`,[organizationId,pr.rows[0].supplier_id,req.params.id,JSON.stringify({createdFrom:'procurement-request'})]); for(const item of b.items) await client.query(`INSERT INTO purchase_order_items(purchase_order_id,inventory_item_id,description,quantity,unit_price,total) VALUES($1,$2,$3,$4,$5,$6)`,[po.rows[0].id,item.inventoryItemId||null,item.description,item.quantity,item.unitPrice,item.quantity*item.unitPrice]); await ctx.dbAudit(client,req,'CREATE','purchase_order',po.rows[0].id,{procurementRequestId:req.params.id}); await ctx.queueEvent(client,req,'procurement.purchase_order.issued',{purchaseOrderId:po.rows[0].id,procurementRequestId:req.params.id,supplierId:pr.rows[0].supplier_id}); await client.query('COMMIT'); return reply.code(201).send(po.rows[0]);}catch(e){await client.query('ROLLBACK');throw e}finally{client.release();}
  });

  app.post('/api/domains/purchase-orders/:id/receive',async(req:any,reply:any)=>{
    write(req); if(!requireDb(reply))return; const b=z.object({receipts:z.array(z.object({itemId:z.string().uuid(),batchNumber:z.string().min(1),quantity:z.number().positive(),expiryDate:z.string().optional(),location:z.string().optional()})).min(1)}).parse(req.body||{}); const organizationId=oid(req)!; const client=await pool!.connect(); try{await client.query('BEGIN'); const po=await client.query(`SELECT * FROM purchase_orders WHERE id=$1 AND organization_id=$2 FOR UPDATE`,[req.params.id,organizationId]); if(!po.rowCount){await client.query('ROLLBACK');return reply.code(404).send({error:'Purchase order not found'});} for(const rec of b.receipts){ const item=await client.query(`SELECT id FROM inventory_items WHERE id=$1 AND organization_id=$2`,[rec.itemId,organizationId]); if(!item.rowCount)throw Object.assign(new Error('Inventory item does not belong to the organization'),{statusCode:409}); let batch=await client.query(`SELECT * FROM inventory_batches WHERE item_id=$1 AND batch_number=$2 FOR UPDATE`,[rec.itemId,rec.batchNumber]); let batchRow:any; if(batch.rowCount){await client.query(`UPDATE inventory_batches SET quantity=quantity+$1,expiry_date=COALESCE($2,expiry_date),location=COALESCE($3,location) WHERE id=$4`,[rec.quantity,rec.expiryDate||null,rec.location||null,batch.rows[0].id]); batchRow=(await client.query(`SELECT * FROM inventory_batches WHERE id=$1`,[batch.rows[0].id])).rows[0];}else{batchRow=(await client.query(`INSERT INTO inventory_batches(item_id,batch_number,expiry_date,quantity,location) VALUES($1,$2,$3,$4,$5) RETURNING *`,[rec.itemId,rec.batchNumber,rec.expiryDate||null,rec.quantity,rec.location||null])).rows[0];} await client.query(`INSERT INTO stock_movements(item_id,batch_id,movement_type,quantity,reference_type,reference_id,created_by) VALUES($1,$2,'receipt',$3,'purchase_order',$4,$5)`,[rec.itemId,batchRow.id,rec.quantity,req.params.id,ctx.dbUserId(req)]); } await client.query(`UPDATE purchase_orders SET status='received',received_at=now() WHERE id=$1`,[req.params.id]); await client.query(`UPDATE procurement_requests SET status='received',received_at=now() WHERE id=(SELECT procurement_request_id FROM purchase_orders WHERE id=$1)`,[req.params.id]); await ctx.dbAudit(client,req,'RECEIVE','purchase_order',req.params.id,{receiptCount:b.receipts.length}); await ctx.queueEvent(client,req,'procurement.purchase_order.received',{purchaseOrderId:req.params.id,receiptCount:b.receipts.length}); await client.query('COMMIT'); return {purchaseOrderId:req.params.id,status:'received',receiptCount:b.receipts.length}; }catch(e){await client.query('ROLLBACK');throw e}finally{client.release();}
  });

  app.get('/api/domains/suppliers/:id/performance',async(req:any,reply:any)=>{
    if(!requireDb(reply))return; const organizationId=oid(req); if(!organizationId)return reply.code(400).send({error:'Organization context is required'}); const supplier=await pool!.query(`SELECT * FROM suppliers WHERE id=$1 AND organization_id=$2`,[req.params.id,organizationId]); if(!supplier.rowCount)return reply.code(404).send({error:'Supplier not found'}); const stats=await pool!.query(`SELECT count(*)::int AS orders,count(*) FILTER(WHERE po.status='issued')::int AS issued,count(*) FILTER(WHERE po.status='received')::int AS received,COALESCE(sum(poi.total),0)::numeric AS order_value FROM purchase_orders po LEFT JOIN purchase_order_items poi ON poi.purchase_order_id=po.id WHERE po.organization_id=$1 AND po.supplier_id=$2`,[organizationId,req.params.id]); const history=await pool!.query(`SELECT po.id,po.status,po.created_at AS "createdAt",po.issued_at AS "issuedAt",po.received_at AS "receivedAt",COALESCE(sum(poi.total),0)::numeric AS total FROM purchase_orders po LEFT JOIN purchase_order_items poi ON poi.purchase_order_id=po.id WHERE po.organization_id=$1 AND po.supplier_id=$2 GROUP BY po.id ORDER BY po.created_at DESC LIMIT 100`,[organizationId,req.params.id]); return {supplier:supplier.rows[0],summary:stats.rows[0],history:history.rows};
  });
}
