'use client';
import {useEffect,useMemo,useState} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:4000';
type Row=Record<string,any>;
const groups:any=[['CARE',['patients','appointments','registration','queue','triage','encounters','clinical-notes','diagnoses','orders','care-plans','referrals','follow-up']],['CLINICAL',['laboratory','imaging','pharmacy','nursing','emergency','inpatient','beds','surgery','maternity','pediatrics','immunization','chronic-care']],['FINANCE',['billing','payments','insurance','claims','accounting']],['SUPPLY',['inventory','procurement','suppliers']],['PATIENT',['patient-portal','telemedicine','remote-monitoring','notifications','documents']],['INTELLIGENCE',['ai','analytics','population-health']],['PLATFORM',['staff','facilities','tasks','workflows','interoperability','trust','audit','settings']]];
const pretty=(x:string)=>x.replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function Home(){
 const [token,setToken]=useState(''),[module,setModule]=useState('patients'),[rows,setRows]=useState<Row[]>([]),[dash,setDash]=useState<Row>({}),[status,setStatus]=useState('Connecting');
 async function login(){const r=await fetch(`${API}/api/auth/demo`,{method:'POST'});const d=await r.json();setToken(d.token)}
 async function load(){if(!token)return;setStatus('Loading');const r=await fetch(`${API}/api/${module}`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();setRows(d.data||[]);setStatus(r.ok?'Ready':'Error')}
 async function refreshDash(){if(!token)return;const r=await fetch(`${API}/api/dashboard`,{headers:{Authorization:`Bearer ${token}`}});setDash(await r.json())}
 useEffect(()=>{login()},[]);useEffect(()=>{if(token){load();refreshDash()}},[token,module]);
 return <main><aside><div className="brand"><b>ClinAI</b><span>Connected Healthcare OS</span></div>{groups.map(([g,items]:any)=><section key={g}><small>{g}</small>{items.map((x:string)=><button key={x} className={module===x?'active':''} onClick={()=>setModule(x)}>{pretty(x)}</button>)}</section>)}</aside><div className="content"><header><div><small>COMMAND CENTER</small><h1>Care, operations and intelligence in one place.</h1><p>One connected journey from registration to treatment, payment and follow-up.</p></div><div className="status">● {status}</div></header><div className="metrics">{[['Patients',dash.patients],['Appointments',dash.appointments],['Waiting',dash.waiting],['Critical labs',dash.criticalLabs],['Open tasks',dash.openTasks],['Unpaid',dash.unpaid]].map(([n,v])=><div className="metric" key={String(n)}><strong>{v??0}</strong><span>{n}</span></div>)}</div><div className="grid"><section className="panel"><div className="panelhead"><div><small>WORKSPACE</small><h2>{pretty(module)}</h2></div><button onClick={()=>{load();refreshDash()}}>Refresh</button></div><Action module={module} token={token} done={()=>{load();refreshDash()}}/><div className="list">{rows.length?rows.map(r=><article key={r.id}><div><b>{r.firstName?`${r.firstName} ${r.lastName}`:r.name||r.description||r.type||r.code||r.template||r.status||'Record'}</b><span>{r.patientNumber||r.phone||r.priority||r.status||r.createdAt||''}</span></div><em>{r.status||''}</em></article>):<div className="empty">No records yet.</div>}</div></section><section className="panel"><div className="panelhead"><div><small>CONNECTED CARE</small><h2>Clinical journey</h2></div></div>{['Registration','Check-in & Queue','Triage & Vitals','Encounter','Orders','Lab / Imaging','Pharmacy','Billing','Discharge','Follow-up'].map((x,i)=><div className="journey" key={x}><i>{i+1}</i><span>{x}</span><em>{i<4?'active':'connected'}</em></div>)}</section></div></div></main>}
function Action({module,token,done}:{module:string,token:string,done:()=>void}){const [d,setD]=useState<Row>({}),[busy,setBusy]=useState(false);const fields:any={patients:[['firstName','First name'],['lastName','Last name'],['phone','Phone']],appointments:[['patientId','Patient ID'],['startAt','Start ISO']],encounters:[['patientId','Patient ID'],['reason','Reason']],triage:[['patientId','Patient ID'],['chiefComplaint','Chief complaint']],orders:[['patientId','Patient ID'],['code','Code'],['description','Description']],laboratory:[['patientId','Patient ID'],['code','Test code']],pharmacy:[['patientId','Patient ID'],['medicationCode','Medication code']],billing:[['patientId','Patient ID'],['description','Charge description']],payments:[['invoiceId','Invoice ID'],['amount','Amount']],referrals:[['patientId','Patient ID'],['reason','Referral reason']],inventory:[['name','Item name'],['quantity','Quantity']]};const fs=fields[module];if(!fs)return <div className="hint">This module is connected to ClinAI's shared domain and workflow engine. Use its specialized API/workflow endpoints for operational actions.</div>;async function submit(){setBusy(true);let url=`${API}/api/${module}`,body={...d};if(module==='triage'){url=`${API}/api/triage`;body={...d,acuity:d.acuity||'routine',temperature:d.temperature?Number(d.temperature):undefined,systolic:d.systolic?Number(d.systolic):undefined,diastolic:d.diastolic?Number(d.diastolic):undefined}}if(module==='orders')body={patientId:d.patientId,category:d.category||'laboratory',code:d.code||'GENERAL',description:d.description,priority:d.priority||'routine'};const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(body)});setBusy(false);if(r.ok){setD({});done()}else alert((await r.json()).error||'Request failed')}return <div className="quick">{fs.map(([k,p]:any)=><input key={k} placeholder={p} value={d[k]||''} onChange={e=>setD({...d,[k]:e.target.value})}/>)}{module==='orders'&&<select value={d.category||'laboratory'} onChange={e=>setD({...d,category:e.target.value})}><option>laboratory</option><option>imaging</option><option>medication</option><option>procedure</option></select>}{module==='triage'&&<select value={d.acuity||'routine'} onChange={e=>setD({...d,acuity:e.target.value})}><option>routine</option><option>urgent</option><option>emergency</option></select>}<button disabled={busy} onClick={submit}>{busy?'Saving…':'Create'}</button></div>}
