import fs from 'node:fs';
import assert from 'node:assert/strict';
import path from 'node:path';
const root=path.resolve(new URL('..',import.meta.url).pathname);
const api=fs.readFileSync(path.join(root,'services/api/src/main.ts'),'utf8');
const page=fs.readFileSync(path.join(root,'apps/web/app/page.tsx'),'utf8');
const css=fs.readFileSync(path.join(root,'apps/web/app/globals.css'),'utf8');
const modules=[...api.match(/const modules = \[(.*?)\] as const;/s)[1].matchAll(/'([^']+)'/g)].map(x=>x[1]);
const defs=new Set([...page.matchAll(/\{key:'([^']+)'/g)].map(x=>x[1]));
for(const m of modules) if(m!=='command-center') assert(defs.has(m),`Missing frontend module: ${m}`);
const routes=[...api.matchAll(/app\.(get|post|put|patch|delete)\('([^']+)'/g)].map(x=>`${x[1].toUpperCase()} ${x[2]}`);
const dup=routes.filter((x,i)=>routes.indexOf(x)!==i);assert.equal(dup.length,0,`Duplicate routes: ${dup.join(', ')}`);
assert.equal((api.match(/,\s*\)/g)||[]).length,0,'Trailing SQL commas remain');
for(const x of ['clinai-logo.png','clinai-icon.png','favicon.ico']) assert(page.includes(x)||fs.existsSync(path.join(root,'apps/web/public',x)),`Brand asset missing: ${x}`);
for(const x of ['desktop-sidebar','tablet-rail','mobile-bottom-nav','nav-drawer','mobile-search']) assert(css.includes('.'+x),`Responsive class missing: ${x}`);
const forbidden=['FST_ERR','developer note','implementation note','TODO:'];for(const x of forbidden) assert(!page.toLowerCase().includes(x.toLowerCase()),`Visible developer wording: ${x}`);
for(const x of ['/api/patients/:id/360/full','/api/patients/:id/timeline','/api/patient-journey/:id','/api/workspaces/:module','/api/referrals/:id/transfers','/api/facilities/:facilityId/beds','/api/imaging/studies','/api/medication-reconciliation']) assert(api.includes(x),`Missing connected workflow route: ${x}`);
console.log(`ClinAI completion audit passed: ${modules.length} modules, ${routes.length} routes, no duplicate routes, no SQL trailing-comma pattern.`);
